name: "Bumper - PostgreSQL Migration Analyzer"
description: "Analyzes PostgreSQL migrations for potential lock issues and posts results as PR comments"
author: "Your Name"

branding:
  icon: "database"
  color: "blue"

inputs:
  anthropic-api-key:
    description: "Anthropic API key"
    required: true
  github-token:
    description: "GitHub token for posting PR comments"
    required: true
  migration-paths:
    description: "Glob patterns for migration files (comma-separated)"
    required: false
    default: "migrations/**/*.sql,migrations/**/*.ts,migrations/**/*.js,src/database/migrations/**/*.ts,src/database/migrations/**/*.js,src/database/migrations/**/*.sql"

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "20"

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        pnpm install --frozen-lockfile

    - name: Get changed migration files
      id: changed-files
      shell: bash
      run: |
        PATTERNS="${{ inputs.migration-paths }}"
        IFS=',' read -ra PATTERN_ARRAY <<< "$PATTERNS"

        CHANGED_FILES=""
        for pattern in "${PATTERN_ARRAY[@]}"; do
          pattern=$(echo "$pattern" | xargs)  # trim whitespace
          FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD -- "$pattern" 2>/dev/null || true)
          if [ -n "$FILES" ]; then
            CHANGED_FILES="$CHANGED_FILES $FILES"
          fi
        done

        CHANGED_FILES=$(echo "$CHANGED_FILES" | xargs)  # trim and normalize whitespace

        if [ -z "$CHANGED_FILES" ]; then
          echo "has_migrations=false" >> $GITHUB_OUTPUT
        else
          echo "has_migrations=true" >> $GITHUB_OUTPUT
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Analyze migrations
      if: steps.changed-files.outputs.has_migrations == 'true'
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
      run: |
        node ${{ github.action_path }}/analyze.js ${{ steps.changed-files.outputs.files }} > /tmp/analysis.md

    - name: Post PR comment
      if: steps.changed-files.outputs.has_migrations == 'true'
      uses: actions/github-script@v8
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const fs = require('fs');
          const analysis = fs.readFileSync('/tmp/analysis.md', 'utf8');

          const body = `## 🚧 Bumper\n\n${analysis}\n\n---\n<sub>Generated by [Bumper](https://github.com/huangkaiw3n/bumper)</sub>`;

          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const botComment = comments.find(c =>
            c.user.type === 'Bot' &&
            c.body.includes('## 🚧 Bumper')
          );

          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
          }
